package pow

import (
	"testing"

	"zycord/core/types"
	"zycord/spec"
)

// I8, part two: what a miner's control of its own timestamps buys.
//
// A miner writes Header.Time itself. Nothing verifies it against a clock —
// consensus cannot, since there is no clock in consensus — so the only things
// holding it are CheckMedianTime below and IsTooFarAhead above, and the second
// of those is a WITHHOLDING rule rather than a rejection rule. The question
// this file asks is what is left inside those two fences.

// TestTheMedianWindowIsEvenSizedEarlyInTheChain records a real asymmetry rather
// than a defect, because it took a while to establish which it was and the next
// reader should not have to repeat that.
//
// Params.Validate requires MedianTimeBlocks to be ODD, and says why: "so the
// median is unambiguous". With an odd count, times[len/2] is the true middle
// element and the choice of convention does not arise.
//
// But MedianTime does not always see MedianTimeBlocks headers. It truncates:
//
//	n := p.MedianTimeBlocks
//	if len(recent) < n { n = len(recent) }
//
// so for the first MedianTimeBlocks-1 blocks of the chain, and for any caller
// that supplies a shorter window, the window is whatever length it is — even
// lengths included. On an even window times[len/2] is the UPPER of the two
// middle elements, which is the higher-median convention.
//
// This is not a defect, and the test asserts the reason it is not: the
// convention is a pure function of the window, so every node computes the same
// value from the same headers and there is no fork. The bound it produces is
// also the STRICTER of the two conventions — a higher median is a higher floor
// on the next timestamp — so the truncation cannot be used to date a block
// EARLIER than a lower-median implementation would have allowed.
//
// What would be a defect is a second implementation choosing the lower median,
// which would accept a header this one rejects. That is a cross-implementation
// hazard and it is recorded in I8's write-up rather than fixed here, because
// fixing it means writing the convention into the spec, not changing the code.
func TestTheMedianWindowIsEvenSizedEarlyInTheChain(t *testing.T) {
	p := spec.Devnet()
	if p.MedianTimeBlocks%2 == 0 {
		t.Fatalf("MedianTimeBlocks is %d; Validate is supposed to keep it odd", p.MedianTimeBlocks)
	}

	// A two-header window: an even length, reachable at height 2 of any chain.
	recent := []types.Header{
		{Height: 0, Time: 100},
		{Height: 1, Time: 200},
	}
	got := MedianTime(recent, p)

	// The higher-median convention. Asserted explicitly so that a change of
	// convention breaks a test rather than silently changing a consensus
	// bound.
	if got != 200 {
		t.Fatalf("median of {100,200} is %d; this implementation takes the UPPER"+
			" middle element and consensus depends on it staying that way", got)
	}

	// It is deterministic: the same window always gives the same answer, which
	// is what makes a convention safe even when it is arbitrary.
	for i := 0; i < 8; i++ {
		if MedianTime(recent, p) != got {
			t.Fatal("MedianTime is not deterministic over a fixed window")
		}
	}

	// And it is the stricter bound: a header at exactly the lower middle
	// element must be REJECTED, which is what "stricter" means operationally.
	h := types.Header{Height: 2, Time: 100}
	if err := CheckMedianTime(h, recent, p); err == nil {
		t.Fatal("a header dated at the lower middle element was accepted;" +
			" the even-window convention is looser than advertised")
	}
}

// TestMedianTimeIsNotFooledByOrderingAsserts that the median is over VALUES and
// not over the order headers arrive in.
//
// A miner controls the timestamps of the blocks it produces, and on a chain
// where it produces several of the last MedianTimeBlocks blocks it controls
// several of the samples. If MedianTime were sensitive to position rather than
// to value — if it took the middle of the window rather than the middle of the
// sorted values — a miner could place a single extreme timestamp at the
// midpoint and move the bound by an arbitrary amount.
//
// It sorts, so it is not. This drives the point: every permutation of one
// multiset of timestamps must give one answer.
func TestMedianTimeIsNotFooledByOrdering(t *testing.T) {
	p := spec.Devnet()

	// An odd window, so the median is the true middle.
	base := []uint64{10, 20, 30, 40, 50}
	mk := func(times []uint64) []types.Header {
		hs := make([]types.Header, len(times))
		for i, tm := range times {
			hs[i] = types.Header{Height: uint64(i), Time: tm}
		}
		return hs
	}
	want := MedianTime(mk(base), p)
	if want != 30 {
		t.Fatalf("median of {10,20,30,40,50} is %d, want 30", want)
	}

	// Every permutation, generated by rotation and by moving the extreme into
	// each slot. A position-sensitive implementation disagrees on at least one.
	perms := [][]uint64{
		{50, 40, 30, 20, 10},
		{30, 10, 50, 20, 40},
		{10, 50, 20, 40, 30},
		{50, 10, 20, 30, 40},
		{20, 30, 40, 50, 10},
	}
	for _, perm := range perms {
		if got := MedianTime(mk(perm), p); got != want {
			t.Errorf("permutation %v gives median %d, want %d — the median is"+
				" position-sensitive and a miner can place one extreme sample"+
				" at the midpoint to move it", perm, got, want)
		}
	}
}

// TestBackdatingIsBoundedByTheMedianAndTheClamp is the backdating attack stated
// end to end.
//
// The rule permits a block dated earlier than its parent — CheckMedianTime
// bounds against the MEDIAN, not against the parent — and NextTarget's comment
// explains at length why the solve time is therefore signed. What is asserted
// here is the operational consequence a miner cares about: how far back a block
// may actually be dated, and that the answer is a function of the median alone.
//
// This is deliberately a bound on the RULE and not a simulation of the
// controller. core/pow/backdate_sweep_test.go already sweeps the controller; a
// second sweep would duplicate it. What was missing is the statement that the
// floor is exactly MedianTime+1 and that nothing else moves it.
func TestBackdatingIsBoundedByTheMedianAndTheClamp(t *testing.T) {
	p := spec.Devnet()

	// A window whose last block is far ahead of the median: the maximally
	// favourable case for a backdater, since the gap between the parent's
	// timestamp and the median is the room it has to work in.
	recent := []types.Header{
		{Height: 0, Time: 1000},
		{Height: 1, Time: 1010},
		{Height: 2, Time: 1020},
		{Height: 3, Time: 5000},
		{Height: 4, Time: 9000}, // the parent, far ahead
	}
	median := MedianTime(recent, p)

	// Exactly at the median: refused. The rule is `<=`, so the median itself
	// is not a legal timestamp.
	if err := CheckMedianTime(types.Header{Height: 5, Time: median}, recent, p); err == nil {
		t.Error("a header dated exactly at the median was accepted; the bound is supposed to be strict")
	}
	// One below: refused.
	if err := CheckMedianTime(types.Header{Height: 5, Time: median - 1}, recent, p); err == nil {
		t.Error("a header dated below the median was accepted")
	}
	// One above: accepted, and this is the floor.
	if err := CheckMedianTime(types.Header{Height: 5, Time: median + 1}, recent, p); err != nil {
		t.Errorf("median+1 was refused (%v); the floor is not where it is documented to be", err)
	}

	// The floor does not depend on the parent's timestamp at all. That is the
	// property that makes backdating possible in the first place, and it is
	// worth pinning: a reader who assumes "later than the parent" is a rule
	// will misjudge every timestamp argument downstream of here.
	parent := recent[len(recent)-1].Time
	if median >= parent {
		t.Fatalf("this fixture no longer exercises backdating: median %d, parent %d", median, parent)
	}
	backdated := types.Header{Height: 5, Time: median + 1}
	if backdated.Time >= parent {
		t.Fatal("the fixture's median+1 is not actually before the parent")
	}
	if err := CheckMedianTime(backdated, recent, p); err != nil {
		t.Errorf("a block dated %d before its parent was refused (%v);"+
			" the signed-solve-time analysis in NextTarget assumes it is allowed",
			parent-backdated.Time, err)
	}
}

// TestTheFutureLimitWithholdsRatherThanRejects pins the distinction the rest of
// the system depends on.
//
// IsTooFarAhead is not a validity rule. A header far in the future is WITHHELD
// — set aside until the clock catches up — and never rejected, because
// rejecting it would make validity depend on the receiving node's clock and two
// nodes with skewed clocks would disagree about a block's validity, which is a
// fork. This test states that CheckWork and CheckMedianTime are indifferent to
// how far ahead a timestamp is, so the withholding is genuinely the only
// consequence.
func TestTheFutureLimitWithholdsRatherThanRejects(t *testing.T) {
	p := spec.Devnet()
	now := uint64(1_000_000)

	recent := []types.Header{
		{Height: 0, Time: now - 100},
		{Height: 1, Time: now - 50},
		{Height: 2, Time: now - 10},
	}

	// A timestamp far past the future limit.
	far := types.Header{
		Version: types.HeaderVersion,
		Height:  3,
		Time:    now + p.FutureTimeLimitSeconds + 10_000,
		Target:  p.GenesisTarget,
	}

	if !IsTooFarAhead(far, now, p) {
		t.Fatal("the fixture is not actually too far ahead")
	}
	// ...is nonetheless fine by the median rule.
	if err := CheckMedianTime(far, recent, p); err != nil {
		t.Errorf("the median rule rejected a far-future header (%v); it must be"+
			" indifferent, or validity depends on the receiver's clock", err)
	}

	// The boundary is exactly `now + limit`: at the limit it is acceptable,
	// one past it is withheld. An off-by-one here is a block that two nodes
	// treat differently at the same instant.
	at := far
	at.Time = now + p.FutureTimeLimitSeconds
	if IsTooFarAhead(at, now, p) {
		t.Error("a header exactly at the future limit was withheld; the boundary is inclusive")
	}
	past := far
	past.Time = now + p.FutureTimeLimitSeconds + 1
	if !IsTooFarAhead(past, now, p) {
		t.Error("a header one second past the limit was not withheld")
	}
}

// TestAnAbsurdTimestampCannotSwingTheRetargetBeyondTheClamp is the difficulty
// half of the timestamp question.
//
// A miner that controls one block's timestamp controls one sample of the LWMA
// window. The per-sample clamp is what bounds the damage, and the property
// worth asserting is that it bounds it SYMMETRICALLY: a timestamp at either
// extreme of uint64 must move the next target by no more than the clamp
// permits, and must not overflow, underflow or panic on the way.
//
// The extremes are the point. Header.Time is attacker-chosen and unvalidated in
// magnitude, so 0 and 2^64-1 are both reachable values that a peer can put on
// the wire, and the subtraction inside NextTarget is over uint64.
func TestAnAbsurdTimestampCannotSwingTheRetargetBeyondTheClamp(t *testing.T) {
	p := spec.Devnet()

	// An honest, evenly spaced window as the baseline.
	n := int(p.DifficultyWindow) + 1
	honest := make([]types.Header, n)
	for i := range honest {
		honest[i] = types.Header{
			Height: uint64(i),
			Time:   uint64(i) * p.TargetBlockSeconds,
			Target: p.GenesisTarget,
		}
	}
	baseline := NextTarget(honest, p)

	// The clamp bounds against the LAST block's target, so those are the
	// bounds every variant must respect.
	last := honest[len(honest)-1].Target
	upper := last.MulDiv64(p.DifficultyClampFactor, 1)
	lower, _ := last.Div64(p.DifficultyClampFactor)

	for _, tc := range []struct {
		name string
		time uint64
	}{
		{"zero", 0},
		{"one", 1},
		{"max uint64", ^uint64(0)},
		{"max minus one", ^uint64(0) - 1},
		{"just below the parent", (uint64(n) - 2) * p.TargetBlockSeconds},
		{"far future", 1 << 62},
	} {
		w := make([]types.Header, n)
		copy(w, honest)
		// The attacker's own block is the most recent one, which carries the
		// largest LWMA weight and is therefore the most valuable slot.
		w[len(w)-1].Time = tc.time

		got := NextTarget(w, p)

		if got.Gt(upper) {
			t.Errorf("%s: next target %s exceeds the per-block clamp ceiling %s",
				tc.name, got.String(), upper.String())
		}
		if got.Lt(lower) {
			t.Errorf("%s: next target %s is below the per-block clamp floor %s",
				tc.name, got.String(), lower.String())
		}
		if got.Gt(p.MaxTarget) {
			t.Errorf("%s: next target exceeds MaxTarget", tc.name)
		}
		if got.IsZero() {
			t.Errorf("%s: next target is zero — no hash can ever satisfy it", tc.name)
		}
		t.Logf("%s: baseline %s -> %s", tc.name, baseline.String(), got.String())
	}
}
