// Code generated by vendor.sh. DO NOT EDIT.

package randomx

// The vendored upstream, identified three ways: the tag a human reads, the
// commit a human verifies, and the tree hash a test recomputes.
//
// This file exists to be a PACKAGE-LEVEL file that changes whenever upstream/
// changes. Go's build cache does not see into upstream/ — see vendor.sh — so
// without something like this, editing the vendored C++ leaves a stale object
// in the cache and every test measures the code you replaced.
const (
	UpstreamTag      = "v2.0.1"
	UpstreamCommit   = "aaafe71322df6602c21a5c72937ac284724ae561"
	UpstreamTreeHash = "822401d806b4b8c172527c3fb2c1397d3d57e6dee2b7d753ef3e038610c9ab90"
)
