// Code generated by vendor.sh. DO NOT EDIT.

package randomx

// The vendored upstream, identified three ways: the tag a human reads, the
// commit a human verifies, and the tree hash a test recomputes.
//
// This file exists to be a PACKAGE-LEVEL file that changes whenever upstream/
// changes. Go's build cache does not see into upstream/ — see vendor.sh — so
// without something like this, editing the vendored C++ leaves a stale object
// in the cache and every test measures the code you replaced.
const (
	UpstreamTag      = "v1.2.3"
	UpstreamCommit   = "12f2c2ffe2108d6cf54c391fee33c8bc3646cdab"
	UpstreamTreeHash = "4830868f9369ba7fc64c0be8f4fabee1a18c626009cb85d942aa8a1be6b61225"
)
