//go:build randomx

/* Generated by vendor.sh. cgo compiles only the package directory, never a
   subdirectory, so each upstream translation unit gets a one-line shim here.
   Do not edit; edit vendor.sh. */
#include "upstream/cpu.cpp"
