#!/bin/sh
# Vendor RandomX into upstream/, byte-identical to a pinned tag, and generate
# the cgo shims that compile it.
#
# This is a maintenance script, not a build step: `make build` must never touch
# the network, and the vendored tree is committed. Run it only to move to a new
# upstream tag, and review the resulting diff as consensus code — the work
# function is what a network is, so a change here is a change of chain.
#
# The upstream/ tree is a byte-identical copy of the tag's src/ directory with
# the test programs removed. Keeping it unedited is what makes auditing it a
# `diff` against the tag rather than an act of faith, so DO NOT PATCH IT: if a
# fix is needed, take it upstream or carry it in a shim.
set -eu

REPO=https://github.com/tevador/RandomX.git
TAG=v1.2.3
COMMIT=12f2c2ffe2108d6cf54c391fee33c8bc3646cdab

cd "$(dirname "$0")"
here=$(pwd)
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

git clone --quiet "$REPO" "$tmp/RandomX"
git -C "$tmp/RandomX" checkout --quiet "$COMMIT"
got=$(git -C "$tmp/RandomX" rev-parse HEAD)
[ "$got" = "$COMMIT" ] || { echo "commit mismatch: $got != $COMMIT" >&2; exit 1; }

rm -rf upstream
mkdir -p upstream
# src/ minus the test programs, which have their own mains and are not library
# code. Their VECTORS are reproduced in Go, in randomx_test.go.
(cd "$tmp/RandomX/src" && find . -type f ! -path './tests/*' -print0 | tar -cf - --null -T -) \
  | (cd upstream && tar -xf -)
cp "$tmp/RandomX/LICENSE" upstream/LICENSE

# The sources CMakeLists.txt compiles, split the way cgo needs them: portable
# ones always, arch-specific ones behind Go's own _GOARCH filename constraints.
portable_c="argon2_ref.c argon2_ssse3.c argon2_avx2.c virtual_memory.c argon2_core.c reciprocal.c blake2/blake2b.c"
portable_cc="aes_hash.cpp bytecode_machine.cpp cpu.cpp dataset.cpp soft_aes.cpp
             vm_interpreted.cpp allocator.cpp assembly_generator_x86.cpp instruction.cpp
             randomx.cpp superscalar.cpp vm_compiled.cpp vm_interpreted_light.cpp
             blake2_generator.cpp instructions_portable.cpp virtual_machine.cpp
             vm_compiled_light.cpp"

rm -f shim_*.c shim_*.cc shim_*.S
# Every shim carries the `randomx` build constraint. Without it cmd/go hands
# the C and assembly sources to the compiler even in a CGO_ENABLED=0 build and
# refuses to build the package at all, which would put a C toolchain back on
# the critical path for `go build ./...` — the exact thing the tag prevents.
banner='//go:build randomx

/* Generated by vendor.sh. cgo compiles only the package directory, never a
   subdirectory, so each upstream translation unit gets a one-line shim here.
   Do not edit; edit vendor.sh. */'

for f in $portable_c; do
  out="shim_$(echo "$f" | tr '/' '_' | sed 's/\.c$//').c"
  printf '%s\n#include "upstream/%s"\n' "$banner" "$f" > "$out"
done
for f in $portable_cc; do
  printf '%s\n#include "upstream/%s"\n' "$banner" "$f" > "shim_${f%.cpp}.cc"
done

# Arch-specific. The _amd64/_arm64 suffixes are Go build constraints and apply
# to C, C++ and assembly sources exactly as they do to Go ones.
printf '%s\n#include "upstream/jit_compiler_x86.cpp"\n' "$banner" > shim_jit_x86_amd64.cc
printf '%s\n#include "upstream/jit_compiler_x86_static.S"\n' "$banner" > shim_jit_x86_static_amd64.S
printf '%s\n#include "upstream/jit_compiler_a64.cpp"\n' "$banner" > shim_jit_a64_arm64.cc
printf '%s\n#include "upstream/jit_compiler_a64_static.S"\n' "$banner" > shim_jit_a64_static_arm64.S

tree=$(cd upstream && find . -type f ! -name LICENSE -print0 | sort -z \
  | xargs -0 shasum -a 256 | shasum -a 256 | cut -d' ' -f1)

{
  echo "upstream:  $REPO"
  echo "tag:       $TAG"
  echo "commit:    $COMMIT"
  echo "vendored:  src/ minus tests/, unmodified"
  echo "tree-hash: $tree"
  echo
  echo "Verify with: sh vendor.sh && git diff --exit-code -- upstream"
} > PINNED

# pinned.go is not documentation. It is what makes Go's build cache correct.
#
# THE HAZARD, because it cost a session to find and it is completely silent:
# the shims #include from upstream/, which is a SUBDIRECTORY, and Go's build
# cache hashes only the files in the package directory. Editing anything under
# upstream/ therefore does not invalidate the cache, and `go test` happily runs
# a binary built from the previous contents. Every mutation test against the
# vendored C++ passes, the engine looks correct under a deliberately broken
# code generator, and nothing anywhere reports a problem.
#
# Writing the tree hash into a package-level Go file closes it: re-vendoring
# rewrites this file, the package's own hash changes, and the cache
# invalidates. A hand edit to upstream/ still would not — which is what
# TestVendoredTreeMatchesPinned is for, and why upstream/ must not be patched.
cat > pinned.go <<GO
// Code generated by vendor.sh. DO NOT EDIT.

package randomx

// The vendored upstream, identified three ways: the tag a human reads, the
// commit a human verifies, and the tree hash a test recomputes.
//
// This file exists to be a PACKAGE-LEVEL file that changes whenever upstream/
// changes. Go's build cache does not see into upstream/ — see vendor.sh — so
// without something like this, editing the vendored C++ leaves a stale object
// in the cache and every test measures the code you replaced.
const (
	UpstreamTag      = "$TAG"
	UpstreamCommit   = "$COMMIT"
	UpstreamTreeHash = "$tree"
)
GO
gofmt -w pinned.go 2>/dev/null || true

echo "vendored $TAG ($COMMIT)"
