//go:build randomx

package randomx

import (
	"encoding/binary"
	"encoding/hex"
	"testing"

	"zycord/core/pow"
	"zycord/core/types"
	"zycord/core/u256"
	"zycord/spec"
)

// The cross-vector file: "our RandomX is exactly rx/0, and our blob is exactly
// the blob a stock miner searches", enforced rather than asserted in prose.
//
// docs/ARCHITECTURE.md §12 and core/types.PoWInput both said, in as many words,
// that no vector fixed the 43 bytes and their digest against stock XMRig, so
// the layout bound this tree and nothing else. This file is what removes that
// sentence. It is the only place in the repository where the encoding rules of
// §12 are checked against numbers that did not come out of this tree.
//
// # Where every constant below came from, and why that matters
//
// A vector computed with the implementation it is meant to check proves
// nothing: it restates the code in hexadecimal. So each anchor here names its
// source, and none of them is this repository.
//
//   - The (key, input, digest) triples are tevador/RandomX's own, from
//     src/tests/tests.cpp at the tag PINNED names (v1.2.3, commit
//     12f2c2ffe2108d6cf54c391fee33c8bc3646cdab). They are reproduced rather
//     than linked because upstream's test programs have their own mains and
//     the tests/ directory is deliberately not vendored.
//   - The nonce offset 39, the nonce width 4, and the 43-byte minimum blob are
//     read off XMRig's own source: Job::nonceOffset() returns 39 for every
//     RandomX-family algorithm (32 is KAWPOW, 76 GHOSTRIDER, 147 RX_YADA),
//     Job::nonceSize() returns 4 for everything but KAWPOW, and Job::setBlob
//     refuses a blob shorter than nonceOffset() + nonceSize().
//   - The comparison rule is CpuWorker::start's, verbatim:
//     `const uint64_t value = *reinterpret_cast<uint64_t*>(m_hash + i*32 + 24);
//     if (value < job.target())`. Eight bytes at offset 24 of a 32-byte digest,
//     read as a native little-endian uint64. That is the top limb of
//     le256(digest), and it is the whole reason the work check reads the digest
//     little-endian.
//
// # What each tier proves, and what it cannot
//
// There are THREE tiers, ordered by how much of this tree they involve, and the
// separation is the point: a failure in tier 1 means the engine is not rx/0,
// while a failure in tier 2 means the engine is fine and the blob is wrong.
// Collapsing them into one test would make every failure say "something is
// wrong with proof of work".
//
// Tier 1 drives upstream's vectors through pow.Engine.Hash — the CONSENSUS
// interface, keyed by a 32-byte types.Hash — rather than through hashRaw.
// TestOfficialVectors already covers hashRaw, and it has to, because three of
// upstream's four keys are short strings that no types.Hash can carry. But
// hashRaw is not the function consensus calls, and an Engine.Hash that mangled
// its key on the way down would leave TestOfficialVectors green.
//
// Tier 2 is the cross-check proper. It builds the blob the way a stock miner
// would — take the 32-byte seed a pool served, zero everything up to byte 39,
// write the nonce there as four little-endian bytes, hand the 43 bytes to
// RandomX — using only the offsets read off XMRig's source above, and asserts
// the result is BYTE-IDENTICAL to what types.Header.PoWInput produced. Neither
// side reads a constant from the other. This is the assertion that would have
// caught a nonce at offset 32, a big-endian nonce, an eight-byte nonce, or a
// reserved gap filled with anything but zero.
//
// Tier 3 carries the comparison rule the same way: the winning verdict is
// computed once by pow.CheckWork and once by XMRig's `hash[24:32] as LE u64 <
// target` line, and the two must agree on the same nonces rather than merely
// both be plausible.
//
// # There is deliberately no recorded 43-byte digest, and a reader should know why
//
// The obvious fourth thing to do is write down one blob's digest as a hex
// constant and assert it. This file does not, and the omission is a decision
// rather than an oversight.
//
// No upstream vector is 43 bytes long, so such a constant could only be taken
// from THIS engine — which makes it a vector generated by the implementation it
// is meant to check, and that proves nothing beyond restating the code in
// hexadecimal. It would also freeze the wrong thing: it pins one (seed, nonce)
// pair, so it fails loudly when the test's own fixture header changes and stays
// silent about every layout error the fixture happens not to reach.
//
// What tier 2 does instead is stronger on exactly the axis a recorded digest is
// weak: it derives the bytes a SECOND way, from XMRig's published offsets alone,
// and compares all 43 of them for five nonces including both ends of the space.
// A recorded digest would be one sample of one input; the byte comparison is the
// whole string, and it names which byte is wrong when it fails.
//
// # Proven non-vacuous, and by which mutations
//
// A test that cannot fail is worse than no test, and the whole reason this file
// exists is that the check it replaces could not fail: for most of its life
// TestTheSolverAgreesWithCheckWork compared two BOOLEANS, and for almost every
// nonce both are false, so a solver with the nonce at the wrong offset or the
// digest read from the wrong end agreed with the rule on all but a vanishing
// fraction of 2^32 inputs and passed. Every assertion below therefore compares
// bytes, or compares verdicts only over a target loose enough that both
// verdicts occur — and where it compares verdicts it also asserts that both
// occurred, so the comparison cannot degenerate into two constants.
//
// Each mutation below was applied to the tree, run, and reverted. The point of
// recording them is that the next person to change the blob layout can re-run
// them rather than re-derive them.
//
//	M1  nonce offset 39 -> 32, blob 43 -> 36   killed (blob length)
//	M2  nonce offset 39 -> 38, blob still 43   killed (byte 38, three tests)
//	M3  nonce written big-endian at 39         killed (byte 39)
//	M4  reserved byte 32 set to 0x01           killed (gap, three tests)
//	M5  checkWorkWith back to FromBytes        killed (a stock miner's share refused)
//	M6  Solver.Try back to FromBytes           killed (first nonce, disjoint sets)
//	M7  eight-byte nonce written at offset 33  killed (gap and byte 33)
//	M8  PoWSeed zeroes ExtraNonce too          SURVIVES — see below
//	M9  Engine.Hash truncates its key to 31 B  killed (tier 1 alone)
//
// M5 and M6 are the two halves of the change this file was written behind, and
// M6 is the one worth dwelling on: it fails on the FIRST nonce tried, where the
// verdict-comparing test it supersedes would have needed a lucky share to
// notice. M9 is the reason tier 1 is not redundant with TestOfficialVectors —
// under M9 TestOfficialVectors still PASSES, because it calls hashRaw, and
// hashRaw is not what consensus calls.
//
// M8 is recorded as a SURVIVOR rather than omitted, because a mutation nothing
// here catches is a boundary worth writing down. Making PoWSeed zero ExtraNonce
// as well as Nonce — the obvious symmetry, and the wrong one, which would
// collapse every pooled miner onto one seed and silently un-shard every pool —
// passes every test in this file. That is correct scoping rather than a hole:
// this file takes PoWSeed() as an opaque thirty-two bytes on BOTH sides of
// every comparison, so it cannot see inside the seed preimage, and a test that
// could would be duplicating core/types.
//
// Where M8 IS caught is worth stating precisely, because one plausible answer
// is wrong. It is caught by core/types.TestExtraNonceIsInsideTheSeedAndTheNonceIsNot,
// confirmed. It is NOT caught by core/pow.TestTheSolverHashesTheHeadersOwnBlob,
// which passes under M8 despite a comment predicting otherwise — and for the
// same structural reason this file misses it: both sides of that comparison
// reach PoWSeed(), so a change INSIDE the seed moves them together and the
// bytes still match. Any test whose two sides both call PoWSeed is blind to the
// seed's preimage by construction, and only a test that varies ExtraNonce and
// watches the seed can see it.
//
// # Bytes, not verdicts
//
// Every tier compares BYTES. The vacuity that TestTheSolverAgreesWithCheckWork
// carried for most of its life — comparing two booleans, both of which are
// false for almost every nonce, so a wrong-offset or big-endian solver agreed
// with the rule on 2^32 minus a handful of inputs — is the exact failure mode
// this file is written against. A digest comparison has no such escape: there
// is one right answer out of 2^256 and a wrong implementation does not stumble
// onto it.

// TestTheConsensusInterfaceComputesUpstreamsFunction drives an upstream vector
// through pow.Engine.Hash, which is the function every work check in the tree
// calls, rather than through hashRaw, which is the function TestOfficialVectors
// calls and which nothing in consensus calls.
//
// The vector is upstream's test_f — the ISUB_R edge case — and it is used here
// for a property unrelated to that bug: it is the only upstream vector whose
// key is thirty-two bytes of raw material rather than a short ASCII string, so
// it is the only one that can be handed to a types.Hash-keyed interface without
// changing what "the key" means.
//
// THE THIRTY-SECOND BYTE. Upstream's harness keys the cache with N-1 bytes of a
// char[32], so the trailing 0x00 of its key array never reaches RandomX; the
// key is genuinely thirty-one bytes, and TestTheISUBREdgeCase's comment records
// the hour that cost. A types.Hash is thirty-two bytes and cannot express a
// thirty-one-byte key, so this test does NOT reuse that digest. It asserts the
// weaker but still upstream-anchored property that Hash(key) and
// hashRaw(string(key[:])) are the same function of the same thirty-two bytes —
// which is what makes TestOfficialVectors' coverage of hashRaw transfer to the
// interface consensus actually uses. An Engine.Hash that truncated, padded,
// re-encoded or hex-ified its key on the way to hashRaw fails here and passes
// every other test in this package.
func TestTheConsensusInterfaceComputesUpstreamsFunction(t *testing.T) {
	e := mustEngine(t, Options{Keys: 2, MaxVMs: 2})

	// Upstream's test_f input, unchanged: the 76-byte blob from tests.cpp.
	in, err := hex.DecodeString(
		"1010e1eaf8cf067b37b5f0ee031ab23ed1755e090a3af4415830145853e2be3e1f68" +
			"21fed84dae58d00e00da5214d6c1f2d0622e0abd51f9373d04e0b0f8e6d6514d906" +
			"89721c4aac5a9bb0d")
	if err != nil {
		t.Fatal(err)
	}

	// Upstream's test_f key as a full thirty-two bytes, INCLUDING the trailing
	// byte its own harness drops. See the comment above: this is deliberately
	// not the same key upstream hashed, and the assertion below does not depend
	// on it being so.
	var key types.Hash
	copy(key[:], []byte{
		0x77, 0x97, 0x37, 0x3e, 0xa4, 0x63, 0x31, 0x94, 0x64, 0x0b, 0xf8, 0xd8,
		0xc3, 0xb6, 0x67, 0x24, 0xd6, 0xaa, 0x7b, 0xd2, 0xdc, 0x20, 0xe0, 0x09,
		0xdf, 0x2f, 0x8f, 0x17, 0x10, 0xab, 0xe8, 0x00,
	})

	viaInterface := e.Hash(key, in)
	viaRaw := e.hashRaw(string(key[:]), in)
	if viaInterface != viaRaw {
		t.Fatalf("Engine.Hash and Engine.hashRaw disagree for the same thirty-two "+
			"byte key:\n  Hash    %x\n  hashRaw %x\n"+
			"TestOfficialVectors checks hashRaw, and nothing in consensus calls "+
			"hashRaw. If the two are different functions then the upstream vectors "+
			"cover a path this chain never takes.",
			viaInterface, viaRaw)
	}

	// And the thirty-one-byte key upstream actually hashed still reaches
	// upstream's digest through this build, so the equality above is anchored to
	// a real published value rather than to two copies of the same mistake.
	const wantUpstream = "78af2a1864c42abce36d2e8983e13df99b2af0ce1362999af09fab004d4435a8"
	sum := e.hashRaw(string(key[:31]), in)
	if got := hex.EncodeToString(sum[:]); got != wantUpstream {
		t.Fatalf("upstream's own vector does not reproduce here:\n got  %s\n want %s\n"+
			"this build is not computing rx/0, and nothing else in this file means "+
			"anything until that is fixed", got, wantUpstream)
	}
}

// xmrigBlob assembles a hashing blob the way stock XMRig does, from XMRig's
// own numbers and from nothing in this repository.
//
// It is a deliberate, independent re-implementation of types.Header.PoWInput,
// and every constant in it is a literal read off XMRig's source rather than a
// symbol imported from core/types. Importing types.PoWInputNonceOffset here
// would make this function agree with PoWInput by construction and the
// comparison below would be a tautology — which is precisely the shape of test
// that let a wrong layout survive before.
//
// XMRig's side of the contract, restated:
//
//	Job::setBlob   accepts a blob of at least nonceOffset() + nonceSize() bytes
//	Job::nonceOffset()  == 39 for the RandomX family
//	Job::nonceSize()    == 4  for everything but KAWPOW
//	WorkerJob::nonce()  == reinterpret_cast<uint32_t*>(blob + nonceOffset())
//
// The last line is where the little-endian-ness comes from: XMRig writes the
// nonce through a uint32_t pointer into the blob, so on every machine XMRig
// supports the four bytes at offset 39 are the nonce in the host's byte order,
// and every host XMRig supports is little-endian.
func xmrigBlob(seed types.Hash, nonce uint32) []byte {
	const (
		xmrigNonceOffset = 39 // xmrig::Job::nonceOffset(), RandomX family
		xmrigNonceSize   = 4  // xmrig::Job::nonceSize()
	)
	blob := make([]byte, xmrigNonceOffset+xmrigNonceSize)
	// A pool serves the template; here the template is thirty-two bytes of seed
	// and then zeroes up to the nonce, which is what this chain's job blob is.
	copy(blob, seed[:])
	binary.LittleEndian.PutUint32(blob[xmrigNonceOffset:], nonce)
	return blob
}

// crossVectorHeader is a header with every field distinctive, so that a blob
// assertion fails when the layout moves rather than when a field happens to be
// zero. It is not a valid block and does not need to be: PoWInput is a total
// function of a header's bytes.
func crossVectorHeader() types.Header {
	h := types.Header{
		Version: types.HeaderVersion,
		Height:  4242,
		Time:    1_767_225_600,
		PoW: types.PoWSeal{
			Nonce:      0x1F2E3D4C,
			ExtraNonce: 0xC0FFEE01,
			SeedEpoch:  2,
		},
	}
	for i := range h.ParentID {
		h.ParentID[i] = byte(0x10 + i)
	}
	for i := range h.CertRoot {
		h.CertRoot[i] = byte(0x40 + i)
	}
	for i := range h.StateRoot {
		h.StateRoot[i] = byte(0x70 + i)
	}
	return h
}

// TestTheBlobThisTreeBuildsIsTheBlobXMRigSearches is the cross-check the
// blob-layout change shipped without, and the reason this file exists.
//
// Two byte strings are built for the same (seed, nonce): one by
// types.Header.PoWInput, one by xmrigBlob from XMRig's published offsets. They
// must be identical BYTE FOR BYTE, and then hash identically. Neither side
// reads a constant from the other, so there is no edit to core/types that can
// make both move together.
//
// This is the assertion that converts "our blob is XMRig's blob" from a
// paragraph in ARCHITECTURE §12 into a fact CI defends. It catches, and was
// checked to catch, all of: a nonce written at offset 32 or 40; a nonce written
// big-endian; an eight-byte nonce spilling into the reserved gap; a blob of 40
// or 44 bytes; and a reserved gap filled with anything but zero.
func TestTheBlobThisTreeBuildsIsTheBlobXMRigSearches(t *testing.T) {
	e := mustEngine(t, Options{Keys: 1, MaxVMs: 2})

	var key types.Hash
	copy(key[:], "zycord xmrig cross-vector key")

	h := crossVectorHeader()
	// Sweep the nonce, including both ends of the space. A single nonce would
	// let a layout that happens to agree on one value through — an eight-byte
	// nonce write, for instance, is indistinguishable from a four-byte one for
	// every nonce whose high half is zero, which is every nonce a naive test
	// picks.
	for _, nonce := range []uint32{0, 1, 0x1F2E3D4C, 0x80000000, 0xFFFFFFFF} {
		h.PoW.Nonce = nonce
		ours := h.PoWInput()
		theirs := xmrigBlob(h.PoWSeed(), nonce)

		if len(ours) != len(theirs) {
			t.Fatalf("nonce %#x: this tree builds a %d-byte blob, XMRig's offsets "+
				"describe a %d-byte one. XMRig's Job::setBlob refuses anything "+
				"shorter than nonceOffset()+nonceSize(), and hashes every byte of "+
				"whatever is longer, so a length disagreement is a different work "+
				"function.", nonce, len(ours), len(theirs))
		}
		for i := range ours {
			if ours[i] != theirs[i] {
				t.Fatalf("nonce %#x: blob byte %d is %#x here and %#x under XMRig's "+
					"layout\n  ours   %x\n  xmrig  %x\n"+
					"a stock miner hashing its blob and this node hashing ours would "+
					"compute different digests for the same header, so every share "+
					"the miner found would be rejected and every block this node "+
					"sealed would be unmineable by anyone else.",
					nonce, i, ours[i], theirs[i], ours, theirs)
			}
		}

		// Identical bytes must hash identically; asserting it costs one hash and
		// closes the (absurd, but free to exclude) possibility that the engine is
		// reading something other than the slice it was handed.
		if a, b := e.Hash(key, ours), e.Hash(key, theirs); a != b {
			t.Fatalf("nonce %#x: identical blobs hashed to %x and %x", nonce, a, b)
		}
	}
}

// TestTheReservedGapIsZeroInTheBlobXMRigWouldBeServed states the zero-pad rule
// as a fact about the bytes a miner receives rather than as a fact about this
// tree's constructor.
//
// The rule binds implementations rather than blocks — no header field reaches
// bytes 32..38, so no block a node could receive violates it and no fold rule
// could reject one — which is exactly what makes it the rule most likely to be
// got wrong by a second implementation and least likely to be caught. The
// corpus in spec/ folds blocks and a block cannot express this gap.
//
// What binds it here is that the gap is checked on BOTH sides: on the blob this
// tree builds, and on the blob assembled from XMRig's offsets, where the gap is
// zero because the template stops at byte 32 and the nonce starts at 39. An
// implementation that put a version byte, a nonce's high bytes or an
// uninitialised buffer in the gap fails the byte comparison in the test above;
// this one says which seven bytes to look at when it does.
func TestTheReservedGapIsZeroInTheBlobXMRigWouldBeServed(t *testing.T) {
	h := crossVectorHeader()
	for _, nonce := range []uint32{0, 0x80000000, 0xFFFFFFFF} {
		h.PoW.Nonce = nonce
		for i, b := range h.PoWInput()[32:39] {
			if b != 0 {
				t.Fatalf("nonce %#x: blob byte %d is %#x, want zero", nonce, 32+i, b)
			}
		}
		for i, b := range xmrigBlob(h.PoWSeed(), nonce)[32:39] {
			if b != 0 {
				t.Fatalf("nonce %#x: XMRig's blob byte %d is %#x, want zero — the gap "+
					"between a thirty-two byte template and the nonce at 39 is seven "+
					"bytes of nothing, and both sides must agree it is zero",
					nonce, 32+i, b)
			}
		}
	}
}

// xmrigWins is XMRig's share test, transcribed from CpuWorker::start:
//
//	const uint64_t value = *reinterpret_cast<uint64_t*>(m_hash + (i * 32) + 24);
//	if (value < job.target())
//
// Eight bytes at offset 24 of the digest, read as a native (little-endian)
// uint64, strictly less than a 64-bit target. It is written out here rather
// than expressed through u256 so that the transcription is checkable against
// the C++ line above by eye.
func xmrigWins(digest types.Hash, target64 uint64) bool {
	return binary.LittleEndian.Uint64(digest[24:32]) < target64
}

// TestXMRigsShareTestAgreesWithTheConsensusRule closes the loop: the blob is
// right and the engine is right, and this says the COMPARISON is right too.
//
// The claim ARCHITECTURE §12 makes is that a 64-bit Stratum job target is a
// clean truncation of the 256-bit consensus target under the little-endian
// rule, so that every share a stock miner finds satisfies the full check. The
// executable form of the truncation identity itself lives in core/pow; what
// lives here is the other half — that the bytes XMRig compares are the bytes
// the rule's most significant limb is made of.
//
// It is asserted over nonces where the two CAN disagree rather than over random
// ones where they almost never can. A target of all-ones in the top limb makes
// XMRig's test pass for roughly half of all digests, so a rule reading the
// digest from the wrong end disagrees on about half the nonces tried instead of
// on one in 2^64 — which is the difference between a test that fails
// immediately under mutation and one that passes for years.
func TestXMRigsShareTestAgreesWithTheConsensusRule(t *testing.T) {
	e := mustEngine(t, Options{Keys: 1, MaxVMs: 2})

	var key types.Hash
	copy(key[:], "zycord xmrig share-test key")

	// A target whose only non-zero part is the top limb, so that the 256-bit
	// comparison is decided entirely by the eight bytes XMRig looks at and the
	// two rules are answering exactly the same question.
	const target64 = uint64(0x8000_0000_0000_0000)
	var targetBytes [32]byte
	binary.BigEndian.PutUint64(targetBytes[0:8], target64)
	target := u256.FromBytes(targetBytes)

	h := crossVectorHeader()
	h.Target = target

	var agreed, wins int
	for nonce := uint32(0); nonce < 64; nonce++ {
		h.PoW.Nonce = nonce
		digest := e.Hash(key, h.PoWInput())

		// The rule, by the same route consensus takes: le256(digest) <= Target.
		ruleWins := !u256.FromLEBytes(digest).Gt(target)
		// XMRig, by its own line. Its test is strictly-less against a target the
		// pool computed; the rule's is less-or-equal against the consensus
		// target. The boundary between them is one value out of 2^64 and cannot
		// be reached by sixty-four nonces, so a disagreement here is a
		// disagreement about which END of the digest to read, which is the thing
		// worth catching.
		minerWins := xmrigWins(digest, target64)

		if ruleWins != minerWins {
			t.Fatalf("nonce %d: the consensus rule says %v and XMRig's own share "+
				"test says %v for digest %x\n"+
				"the two read opposite ends of the digest and the ends are "+
				"independent, so a chain where they disagree is a chain no stock "+
				"miner can mine and no pool can proxy for.",
				nonce, ruleWins, minerWins, digest)
		}
		agreed++
		if ruleWins {
			wins++
		}
	}

	// ANTI-VACUITY. The loop above compares two booleans, and the lesson of
	// TestTheSolverAgreesWithCheckWork is that two booleans agree trivially when
	// one of the values never occurs. With the top-limb target above, each
	// reading should win about half the time; if every nonce lost, the loop
	// proved only that two functions both said no.
	if wins == 0 {
		t.Fatalf("none of the %d nonces met a target that half of all digests "+
			"should meet: this test compared %d pairs of `false` and cannot fail",
			agreed, agreed)
	}
	if wins == agreed {
		t.Fatalf("all %d nonces met the target: this test compared %d pairs of "+
			"`true` and cannot fail", agreed, agreed)
	}
}

// TestCheckWorkAcceptsWhatAStockMinerWouldSubmit runs the whole path — header,
// blob, engine, little-endian comparison — through the exported rule, for a
// nonce found the way a stock miner finds one.
//
// The nonce is searched with xmrigWins over blobs built by xmrigBlob: XMRig's
// offsets, XMRig's share test, nothing of this tree's except the seed the pool
// would have served and the engine. pow.CheckWork must then accept the header
// carrying that nonce. A tree in which it does not is a tree whose chain is
// unmineable by the only miner anybody runs.
//
// The converse is asserted too, and it is the half that carries the weight: a
// nonce the stock miner REJECTED must be rejected by CheckWork. Without it the
// test passes against a rule that accepts everything.
func TestCheckWorkAcceptsWhatAStockMinerWouldSubmit(t *testing.T) {
	e := mustEngine(t, Options{Keys: 2, MaxVMs: 2})
	p := spec.Devnet()

	h := crossVectorHeader()
	h.Height = 4242
	h.PoW.SeedEpoch = pow.SeedEpochFor(h.Height, p)

	// The key the rule will use. The stock miner is served it as a Stratum
	// seed_hash and never derives it; that is the schedule's whole integration
	// advantage and ARCHITECTURE §12 states it.
	key := pow.KeyFor(h.Height, p)

	// A top-limb-only target, as above, so that a search terminates in a few
	// hashes and both readings are live.
	const target64 = uint64(0x0800_0000_0000_0000)
	var targetBytes [32]byte
	binary.BigEndian.PutUint64(targetBytes[0:8], target64)
	h.Target = u256.FromBytes(targetBytes)

	seed := h.PoWSeed()

	var found, rejected uint32
	var haveFound, haveRejected bool
	for nonce := uint32(0); nonce < 4096; nonce++ {
		digest := e.Hash(key, xmrigBlob(seed, nonce))
		if xmrigWins(digest, target64) {
			if !haveFound {
				found, haveFound = nonce, true
			}
		} else if !haveRejected {
			rejected, haveRejected = nonce, true
		}
		if haveFound && haveRejected {
			break
		}
	}

	// ANTI-VACUITY, and it is not a formality. If the search never finds a
	// share, everything below is skipped and the test passes having asserted
	// nothing — which is exactly how a test of a solver can rot into a test of
	// nothing when a parameter change moves the solve rate.
	if !haveFound {
		t.Fatalf("no nonce below 4096 met a target one part in 32 should meet in " +
			"about 32 tries: either the engine is not producing uniform digests or " +
			"this test has stopped being able to fail")
	}
	if !haveRejected {
		t.Fatal("every nonce below 4096 met the target; the target is not " +
			"discriminating and the acceptance below proves nothing")
	}

	// The share a stock miner would submit must be accepted by the rule.
	h.PoW.Nonce = found
	if err := pow.CheckWork(e, h, p); err != nil {
		t.Fatalf("nonce %#x is a share stock XMRig would have submitted — its own "+
			"share test accepted it against the same target — and CheckWork "+
			"rejects it: %v\n"+
			"this is the failure that makes a chain unmineable: the miner works, "+
			"finds shares, submits them, and every one is refused.", found, err)
	}

	// And the nonce the miner discarded must be refused, or the acceptance above
	// is satisfied by a rule that accepts anything.
	h.PoW.Nonce = rejected
	if err := pow.CheckWork(e, h, p); err == nil {
		t.Fatalf("nonce %#x is one stock XMRig's own share test REJECTED against "+
			"this target, and CheckWork accepted it: the rule is not discriminating "+
			"and its acceptance of nonce %#x above means nothing", rejected, found)
	}
}

// TestTheSolverFindsWhatAStockMinerFindsForTheSameHeader compares the miner
// path against a stock miner BY NONCE rather than by verdict.
//
// pow.Solver.Try and pow.checkWorkWith share no code, which is why
// TestTheSolverAgreesWithCheckWork exists; but for most of its life that test
// compared two booleans, and for almost every nonce both are false, so a solver
// with the nonce at the wrong offset or the digest read from the wrong end
// agreed with the rule on all but a vanishing fraction of inputs and passed.
//
// This compares the SET of winning nonces against a stock miner's, over a
// target loose enough that the set is large. Two implementations that disagree
// about the blob or about the digest's byte order produce disjoint sets, not
// slightly different ones, so the comparison fails on the first nonce either
// finds.
func TestTheSolverFindsWhatAStockMinerFindsForTheSameHeader(t *testing.T) {
	e := mustEngine(t, Options{Keys: 2, MaxVMs: 2})
	p := spec.Devnet()

	h := crossVectorHeader()
	h.Height = 4242
	h.PoW.SeedEpoch = pow.SeedEpochFor(h.Height, p)

	// A quarter of all digests win, so a hundred nonces give about twenty-five
	// members on each side.
	const target64 = uint64(0x4000_0000_0000_0000)
	var targetBytes [32]byte
	binary.BigEndian.PutUint64(targetBytes[0:8], target64)
	h.Target = u256.FromBytes(targetBytes)

	seed := h.PoWSeed()
	key := pow.KeyFor(h.Height, p)
	s := pow.NewSolver(e, h, p)

	var solverWins, minerWins int
	for nonce := uint32(0); nonce < 128; nonce++ {
		ours := s.Try(nonce)
		theirs := xmrigWins(e.Hash(key, xmrigBlob(seed, nonce)), target64)
		if ours != theirs {
			t.Fatalf("nonce %#x: this tree's solver says %v, a stock miner says %v\n"+
				"the two searched the same header against the same target and "+
				"disagree about the answer, so a miner running this solver and a "+
				"miner running XMRig would find disjoint sets of blocks.",
				nonce, ours, theirs)
		}
		if ours {
			solverWins++
		}
		if theirs {
			minerWins++
		}
	}

	// ANTI-VACUITY, and this one is the whole point of the test. The bug being
	// guarded against is a comparison of two constants: if neither side ever
	// won, the loop above compared `false` with `false` 128 times and would pass
	// against a solver reading the nonce from the wrong offset.
	if solverWins == 0 || minerWins == 0 {
		t.Fatalf("solver won %d and stock miner won %d of 128 nonces against a "+
			"target a quarter of digests should meet: this test compared constants "+
			"and cannot fail", solverWins, minerWins)
	}
	if solverWins == 128 || minerWins == 128 {
		t.Fatalf("solver won %d and stock miner won %d of 128: the target is not "+
			"discriminating and this test cannot fail", solverWins, minerWins)
	}
}
