// The workflow is a copy of the Makefile that nothing was comparing.
//
// This file exists because CI carried its own inline copy of the whole-tree
// test command instead of calling the Makefile, and the shape of that defect is
// the one this package was built for: a thing that was correct, complete, and
// connected to nothing that would notice it drifting.
//
// A commit added `-timeout 30m` to the Makefile's `race` target, with a comment
// explaining precisely why Go's ten-minute default is the wrong number for
// `node/mempool` under the race detector. The commit message was "fix race test
// timeout". It did not fix the race test timeout, because
// `.github/workflows/ci.yml` did not call `make race` — it carried its own
// inline `go test -race ./...`, which Go runs at the ten-minute default. So the
// fix landed in one file, the job kept failing in the other, and `main`'s own
// run at that very commit is red for exactly the thing the commit claims to
// have fixed.
//
// Nothing caught it. Not `make lint`, which vets Go and not YAML; not `make ci`,
// whose stages never read the workflow that invokes them; not review, twice. The
// duplication was invisible *because* both copies were correct when written —
// they diverged later, silently, in the direction of a red check everyone had
// learned to skim.
//
// # Why this is a golden list and not a rule
//
// The first three versions of this file tried to *decide* whether a shell
// command invokes a whole-tree `go test`: a prefix match, then a substring
// match, then an anchored regular expression with exemptions for the `windows`
// job and the `desktop` module. Two hostile reviews put nine evasions through
// them, and the ninth was created by the fix for the eighth:
//
//	prefix      `CGO_ENABLED=0 go test ./...`
//	substring   the positive half satisfied by `make test-randomx`
//	prose       `echo 'run make test locally'`
//	quoting     `go test -race "./..."` — invisible once quoted text was
//	            stripped to stop the prose case, which is the previous row's fix
//	            opening the hole
//	wrappers    `timeout 20m go test ./...`, `xvfb-run …`, `nice …`, `sudo …`
//	grouping    `(go test -race ./...)`
//	indirection `sh -c "go test -race ./..."`
//	multi-line  a `\` continuation, and a folded `run: >` body
//	scope       a job id containing `_` inherited the previous job's exemption
//
// None needed special knowledge. That is the answer to whether the surface is
// closable, and CONTRIBUTING.md names the pattern it was following: a check that
// is patched round after round accrues exactly the debt it exists to prevent,
// and "flagged-but-unfixed compounds silently".
//
// So the deciding is gone. What is pinned instead is an equality: **the set of
// CI commands naming the whole-tree package pattern is exactly the set written
// down here.** Equality has no evasions — every command above lands in the
// diff of this list, because every one of them contains `./...`, which is the
// marker of the thing rather than a guess about it.
//
// Two consequences worth stating plainly.
//
// The exemptions stop being logic. The `windows` job and the `desktop` module
// were rules with a granularity, and getting that granularity wrong was itself
// two of the nine findings — a job-wide `desktop` exemption excused a step in
// that job running against the *root* module. They are now five lines of data
// that somebody had to write down. There is no granularity left to get wrong.
//
// Editing the workflow now requires editing this list. That is the cost, and it
// is the point: the failure is a prompt to read this comment before adding a
// whole-tree command, not an assertion about a shell string that may be wrong.
// It is the same trade `spec/vectors` already makes — a golden corpus,
// regenerated by hand, whose diff is the review.
//
// The two known limits, stated rather than discovered — CONTRIBUTING.md's rule
// is to write the conditions next to the number, and "equality has no evasions"
// is true of the nine forms above but not of the property.
//
// False negative: a whole-tree run written WITHOUT the marker is not seen.
//
//	go test -race -timeout 5m ./node/... ./core/... ./sim/... ./wallet/...
//
// Splitting the suite by subtree to parallelise CI is realistic drift, not an
// adversary, and it has that defect's exact shape — a second definition of how
// the tree is tested, free to diverge from the Makefile's. `go test all` is the
// same gap and less likely. Closing it needs a rule about what the package
// arguments MEAN, which is the deciding this file just spent three rounds
// proving it cannot do reliably; the honest position is that the check covers
// the literal pattern and the reviewer covers the rest.
//
// False positive: a step whose
// command merely *mentions* `./...` — an `echo` in a help message, say — lands
// in the list too, because the marker is matched in the raw text and nothing
// here parses shell any more. CONTRIBUTING.md is right that a check firing for a
// benign reason is worse than silence, so the trade is worth naming: the cost is
// one line added to a list, in a file that has no such command today and gains
// one about never; the thing bought is that no shell SYNTAX evades the check,
// which nine measured evasions say the alternative could not offer.
//
// # A job may be a call rather than a list of steps
//
// A job whose body is `uses: ./.github/workflows/<file>` runs that workflow's
// steps, and this file has to follow the call to see them. It is the same
// blindness the parser checks guard against, arriving through the one door they
// did not watch: `parseJobs` still saw the job, so the job list was green, and
// `parseRuns` found no step inside it, so every command it runs left the golden
// list at once. The three `windows` entries went that way when the job was
// extracted into its own file — the commands did not change, the file the
// parser reads did.
//
// The per-job blindness check below is what catches this class, and it caught
// this instance: a job the parser SEES but reaches no command in. That is why
// it is a condition on the reading rather than on a count.
//
// Commands from a called workflow are attributed to the CALLING job, because
// that is the job the golden list names and the one a reader sees in the checks
// list. The callee's own job id is not used: renaming it is invisible to CI's
// caller and must not churn the list here.
//
// Deliberately textual rather than a YAML parse. The tree carries two direct
// dependencies and `go.mod` says that is meant to stay that way, so a YAML
// library would need the dedicated pull request CONTRIBUTING.md requires — to
// read a file this reads in eighty lines.
package wiring_test

import (
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"
)

// workflowPath is the CI definition, relative to this package.
const workflowPath = "../../.github/workflows/ci.yml"

// makefilePath is the file it is required not to duplicate.
const makefilePath = "../../Makefile"

// repoRoot is the repository root, relative to this package. A workflow's
// `uses: ./...` reference is written from there rather than from the file
// carrying it.
const repoRoot = "../.."

// resolver reads a workflow named by a `uses:` reference. It reports false for
// a reference this file will not follow, which covers three cases the caller
// treats alike: a reference outside this repository (a published action, which
// has no steps to read here), one that cannot be read, and one already visited.
//
// A reference that cannot be read is deliberately quiet rather than fatal,
// because the per-job blindness check in TestTheParserStillSeesTheWholeWorkflow
// already reports the consequence — a job reaching no command — and reports it
// against the job a reader has to fix rather than against a path.
type resolver func(ref string) (string, bool)

// localWorkflows resolves `uses:` references naming a workflow in this
// repository, and refuses to follow one twice.
//
// The refusal is the cycle guard: workflow_call is a call graph, so a workflow
// calling one that calls back would otherwise recurse until the stack ends. It
// is per-traversal state, so each walk of the file needs its own resolver — two
// walks sharing one would leave the second blind to everything the first read.
func localWorkflows() resolver {
	seen := map[string]bool{}
	return func(ref string) (string, bool) {
		if !strings.HasPrefix(ref, "./") {
			return "", false
		}
		path := filepath.Join(repoRoot, filepath.Clean(strings.TrimPrefix(ref, "./")))
		if seen[path] {
			return "", false
		}
		seen[path] = true
		b, err := os.ReadFile(path)
		if err != nil {
			return "", false
		}
		return string(b), true
	}
}

// treeWide is the whole-tree package pattern.
//
// It is matched against the command's RAW text, quotes and all. Stripping quotes
// first — which an earlier version did, to stop an `echo` about `go test` firing
// the check — made `go test -race "./..."` invisible, which is ordinary
// defensive shell and the exact thing being guarded. The marker is the marker
// wherever it appears; whether the command is prose is settled by the list
// below, not by parsing shell.
const treeWide = "./..."

// runLine matches a step's `run:` key and captures whatever follows it on the
// same line: either the command itself, or a block-scalar indicator.
var runLine = regexp.MustCompile(`^(\s*)run:\s*(.*?)\s*$`)

// blockScalar matches YAML's literal and folded block indicators — `|`, `>`, and
// their chomping and indentation modifiers — which say the command is on the
// following, more-indented lines rather than this one.
//
// The first version of this file matched only `run: <command>` on one line, so a
// `run: |` step captured the literal "|" as its command and the actual command,
// indented below, was never read. This workflow uses the block form nine times.
var blockScalar = regexp.MustCompile(`^([|>])([-+]?[0-9]*|[0-9]*[-+]?)$`)

// stepStart matches the `- ` that begins a new step, which is where a
// `working-directory:` stops applying.
var stepStart = regexp.MustCompile(`^(\s*)- `)

// workingDir matches a `working-directory:` key, in a step or in a job's
// `defaults.run` block.
//
// It carries the same trailing-comment tolerance as the structural keys, and for
// the same reason: without it, `working-directory: desktop # the separate
// module` dropped the key, and the golden list then reported the desktop
// module's own `go vet ./...` as an unreviewed command running "at the
// repository root". A benign comment, a false accusation, and a wrong
// diagnosis — the same shape as the job-header bug one regex earlier.
var workingDir = regexp.MustCompile(`^\s*working-directory:\s*(\S+)\s*(#.*)?$`)

// jobsKey matches the top-level `jobs:` mapping, at column zero.
//
// The job scan is gated on it because jobHeader describes an indentation, not a
// meaning: `on:` carries `push:` and `pull_request:` at the same two spaces, and
// without this gate they are read as jobs.
var jobsKey = regexp.MustCompile(`^jobs:\s*(#.*)?$`)

// jobHeader matches a job key: two spaces, a name, a colon, nothing else.
//
// The charset is deliberately wide. It was `[a-z][a-z0-9-]*` — no underscore,
// though `pull_request:` two screens above proves the character is idiomatic in
// this very file. An unmatched header made the parser carry the PREVIOUS job's
// name forward, silently attributing one job's steps to another.
var jobHeader = regexp.MustCompile(`^  ([A-Za-z0-9_.-]+):\s*(#.*)?$`)

// stepsKey matches a job's `steps:` list. Steps are read only after it, so that
// a job-level `defaults:` block — which contains a `run:` mapping of its own —
// is not mistaken for a step running the empty command.
//
// All three structural keys tolerate a trailing `# comment`, because without it
// they did not, and the consequence was silence. `steps: # its commands` failed
// to match, so the parser never entered that job and an inline whole-tree race
// run inside it was invisible. One key up, `windows: # the platform job` failed
// jobHeader and re-attributed every windows command to the previous job, firing
// the golden list with the wrong story and a suggested fix that deletes real
// coverage. Annotating a YAML key is ordinary; a check that goes quiet when
// someone does it is the mirror CONTRIBUTING.md warns about.
var stepsKey = regexp.MustCompile(`^\s*steps:\s*(#.*)?$`)

// runKey matches what a step's `run:` key looks like before any indentation
// reasoning is applied, including the unnamed `- run:` form. It is used only to
// ask whether a step the parser produced nothing for *should* have produced
// something.
var runKey = regexp.MustCompile(`^\s*(- )?run:`)

// localWorkflowCall matches a job-level `uses:` naming a reusable workflow.
//
// It is applied only where a job-level key can appear — inside a job and before
// its `steps:` — so it needs no indentation reasoning to tell itself apart from
// the `- uses:` of a step, which cannot occur there. What it does require is the
// leading `./` that marks a workflow in this repository: a published action is
// a `uses:` too, and there is nothing here to read inside one.
var localWorkflowCall = regexp.MustCompile(`^\s*uses:\s*(\S+)\s*(#.*)?$`)

// usesKey matches a step's `uses:` key.
//
// A step that `uses:` an action is exempt from the blindness check, because a
// composite action's `with:` block can carry a `run:` input of its own — a
// string the action consumes, not a command this workflow runs. That exemption
// is what lets the check be per-step and therefore free of any need to know how
// many keys the parser deliberately skips.
var usesKey = regexp.MustCompile(`^\s*(- )?uses:`)

// command is one shell command from the workflow, with the context a reader
// needs in order to judge it.
//
// WorkingDir is part of the identity, not decoration. `desktop/` is a separate
// Go module, so `go test ./...` evaluated there names a different package set
// from the same command at the repository root — the two are different facts
// that read identically, and an earlier version of this file accepted a
// root-module race run because it compared only the job.
type command struct {
	Job        string
	WorkingDir string
	Text       string
}

// readWorkflowCommands returns every shell command in the workflow, tagged with
// the job and working directory it runs under.
func readWorkflowCommands(t *testing.T) []command {
	t.Helper()
	b, err := os.ReadFile(filepath.Clean(workflowPath))
	if err != nil {
		t.Fatalf("reading the workflow: %v", err)
	}
	cmds := parseRuns(string(b), localWorkflows())
	if len(cmds) == 0 {
		t.Fatalf("parsed no run: steps out of %s; the parser has gone stale", workflowPath)
	}
	return cmds
}

// TestTheParserStillSeesTheWholeWorkflow is the obsolescence check, and it is
// the one this file most needs.
//
// The property: **the set of jobs the parser finds is exactly the set of jobs
// the workflow defines.**
//
// Everything else here now rests on the parser. That is the cost of replacing a
// rule with a golden list: the list cannot be argued with, but it can be fed an
// incomplete reading of the file, and a parser that has stopped seeing a job
// reports exactly the same green as a workflow with nothing wrong in it. That is
// the mirror CONTRIBUTING.md tabulates — an instrument whose signal is derived
// from the state the bug corrupts — and it was not hypothetical: `steps:` failed
// to match when someone wrote `steps: # its commands`, so the parser never
// entered that job and an inline whole-tree race run inside it was invisible.
//
// A `len(cmds) == 0` guard does not reach this. It fires only when the parser
// goes blind to the *whole* file, and the failure that matters is going blind to
// one job. So the job names are pinned as data, in the same style as the command
// list: a job that disappears from the parser's view is a diff, and a job that is
// genuinely added is one line plus the thought about whether it runs the whole
// tree.
//
// Two blindness checks sit beside the job names, and they are the half with the
// sharper teeth. Pinning jobs catches blindness at job granularity and is
// structurally incapable of catching it one level down: when `- run:` without a
// `name:` matched no key, `parseJobs` and `parseRuns` still agreed perfectly
// about every job in the file while an inline whole-tree race run inside one of
// those jobs produced no command at all. Both readings were confidently right
// about jobs and silently wrong about a step.
//
//	per step  a step with no `uses:` key, carrying a line that looks like a
//	          `run:` key, that yields no command, is a step the parser cannot
//	          read. That is exactly what an unnamed `- run:` was, and it is what
//	          any future key-regex regression will be, at any indentation.
//
//	per job   every job named above yields at least one command. That is the
//	          other shape: a job the parser SEES but whose steps it cannot
//	          reach, which is what a commented `steps:` key produced.
//
// Both are conditions on the parser's own reading rather than on a number, so
// neither fires when the workflow legitimately changes.
//
// A pinned command count was tried first and replaced, and the reason is the
// point rather than a detail. It worked — it caught the unnamed step — but it
// also fired on every benign edit, and its failure read "recovers 76 commands
// and 75 are expected". The golden lists' churn is the point *because their
// diff is a review*: the reader sees which whole-tree command appeared and
// decides. "76 ≠ 75" is not a review. It says nothing about what changed, and
// the only available response is to increment the constant — and a check whose
// remedy is to reflexively bump a number is a check people learn to skim, which
// is the exact failure this file exists to prevent. CONTRIBUTING.md: a check
// that fires for a benign reason is noise with authority, and worse than
// silence.
//
// The narrower pair gives up detecting a step that was *deleted*. The golden
// list already catches deletion of the five whole-tree commands, the positive
// half catches deletion of `make test` and `make race`, and a deleted `echo`
// step is not worth a red build.
func TestTheParserStillSeesTheWholeWorkflow(t *testing.T) {
	want := []string{
		"build", "vectors", "differential", "fuzz", "randomx",
		"canonical", "desktop", "windows", "reproducible",
	}

	b, err := os.ReadFile(filepath.Clean(workflowPath))
	if err != nil {
		t.Fatalf("reading the workflow: %v", err)
	}
	src := string(b)

	// A fresh resolver for each traversal: they are independent walks of the
	// same file, and the cycle guard is per-resolver state.
	for _, blind := range blindSteps(src, localWorkflows()) {
		t.Errorf("the parser cannot read this step:\n%s\n"+
			"It has what looks like a `run:` key and no `uses:`, and yet produced no\n"+
			"command — so none of the checks in this file apply to whatever it runs.\n"+
			"This is a parser defect, not a workflow defect: fix the reading, and add\n"+
			"the form to TestTheParserSeesTheFormsTheWorkflowUses so it stays fixed.",
			blind)
	}

	got := parseJobs(src)

	reached := map[string]bool{}
	for _, c := range parseRuns(src, localWorkflows()) {
		reached[c.Job] = true
	}

	if len(got) != len(want) {
		t.Errorf("the parser sees %d jobs and %d are written down here:\n"+
			"    sees:    %v\n    written: %v\n"+
			"A job the parser cannot see is a job none of the checks in this file apply\n"+
			"to, and it reports the same green as a job with nothing wrong in it.",
			len(got), len(want), got, want)
	}
	seen := map[string]bool{}
	for _, j := range got {
		seen[j] = true
	}
	for _, j := range want {
		if !seen[j] {
			t.Errorf("the parser no longer sees the %q job.\n"+
				"Either it was renamed or removed — update this list — or the parser has\n"+
				"gone blind to it, in which case nothing else in this file is checking it.", j)
			continue
		}
		if !reached[j] {
			t.Errorf("the parser sees the %q job but reaches none of its commands.\n"+
				"Every job in this workflow runs something. A job whose steps cannot be\n"+
				"read reports the same green as a job with nothing wrong in it — a\n"+
				"commented `steps:` key did exactly this.", j)
		}
	}
	for _, j := range got {
		if !contains(want, j) {
			t.Errorf("the workflow defines a job this list does not name: %q.\n"+
				"Add it — and while you are here, check that it does not run the whole\n"+
				"tree inline.", j)
		}
	}
}

func contains(xs []string, x string) bool {
	for _, v := range xs {
		if v == x {
			return true
		}
	}
	return false
}

// blindSteps returns a rendering of every step that looks like it runs
// something and that the parser could not read.
//
// The property it serves: a step carrying a `run:` key and no `uses:` must
// produce at least one command. An unnamed `- run:` satisfied the first half and
// failed the second — silently, at every indentation — and so would any future
// regression in the key regexes.
//
// It walks the same eachStep as parseRuns, deliberately: a check that segmented
// the file its own way could disagree with the reading it is auditing, and
// then it would be reporting on a workflow nobody runs.
func blindSteps(src string, resolve resolver) []string {
	var blind []string
	eachStep(src, resolve, func(job, defaultWD string, step []string) {
		hasRun, hasUses := false, false
		for _, line := range step {
			if runKey.MatchString(line) {
				hasRun = true
			}
			if usesKey.MatchString(line) {
				hasUses = true
			}
		}
		if !hasRun || hasUses {
			return
		}
		if len(commandsInStep(job, defaultWD, step)) > 0 {
			return
		}
		blind = append(blind, "    job "+job+":\n        "+strings.Join(step, "\n        "))
	})
	return blind
}

// parseJobs returns the job names, in file order. Separate from parseRuns
// because the question it answers is about the parser rather than the commands.
func parseJobs(src string) []string {
	var jobs []string
	inJobs := false
	for _, line := range strings.Split(src, "\n") {
		if jobsKey.MatchString(line) {
			inJobs = true
			continue
		}
		if !inJobs {
			continue
		}
		if m := jobHeader.FindStringSubmatch(line); m != nil {
			jobs = append(jobs, m[1])
		}
	}
	return jobs
}

// TestTheWholeTreeSuitesRunOnlyWhereTheyWereReviewed is the duplication itself,
// stated as an equality.
//
// The property, in one sentence: **every CI command naming the whole-tree
// package pattern is one of the commands written down here, and there are no
// others.**
//
// That is the negative half — no step re-implements what the Makefile defines —
// expressed as an equality rather than as a judgement about shell syntax. See
// the package comment for why: nine evasions got through three generations of
// judgement, one of them introduced by the previous one's fix.
//
// The list is short because the property is narrow, and each entry is an
// exemption someone had to write down and a reviewer had to read:
//
//	windows           GNU make is absent from the `windows-latest` image, so the
//	                  Makefile is not the entry point on that platform.
//	                  CONTRIBUTING.md says so, and that job's own header says so
//	                  at length.
//
//	desktop/          A separate Go module. `./...` evaluated there names a
//	                  package set no target in this Makefile builds, and keeping
//	                  `make ci` unaware of it is why the module is separate. Note
//	                  the two entries carrying `windows` as the job: the desktop
//	                  wallet is built on both runners.
//
// The `build` job appears nowhere in this list, and that absence is the change
// the fix asked for: after routing `tests` through `make test`, no step of that
// job names the whole tree at all — the Makefile does.
//
// Adding a step that runs `./...` fails here. If it belongs — a new platform
// job, a new separate module — add it, and say in the pull request why the
// Makefile is not the entry point for it. If it does not, call the target.
func TestTheWholeTreeSuitesRunOnlyWhereTheyWereReviewed(t *testing.T) {
	// Every reviewed use of the whole-tree pattern in ci.yml. Ordered as the
	// file is.
	want := []command{
		{"desktop", "desktop", "go vet -tags desktop,webkit2_41 ./..."},
		{"desktop", "desktop", "go test -tags desktop,webkit2_41 ./..."},
		{"windows", "", "go vet ./..."},
		{"windows", "", "go test -timeout 30m ./..."},
		{"windows", "desktop", "go test -tags desktop ./..."},
	}

	var got []command
	for _, c := range readWorkflowCommands(t) {
		if strings.Contains(c.Text, treeWide) {
			got = append(got, c)
		}
	}

	// Compared as multisets, not as sequences. Moving two job blocks past each
	// other in the YAML is a pure reorder that changes nothing about what CI
	// runs, and an ordered comparison reported four "command changed" errors for
	// it — four failures naming real commands, none of them a real change. Job
	// and working-directory are already part of each entry's identity, so
	// ordering carries no information that would be lost.
	missing, extra := diff(want, got)
	for _, c := range extra {
		t.Errorf("unreviewed whole-tree command:\n    %s\n%s", show(c), why)
	}
	for _, c := range missing {
		t.Errorf("a reviewed whole-tree command is gone from the workflow:\n    %s\n"+
			"If it was deliberately removed or edited, update the list here too — and if\n"+
			"it was NOT, something is running the whole tree somewhere else now.", show(c))
	}
}

// diff reports the entries of want absent from got and the entries of got absent
// from want, comparing multisets so a duplicated command is not absorbed.
func diff(want, got []command) (missing, extra []command) {
	count := map[command]int{}
	for _, c := range got {
		count[c]++
	}
	for _, c := range want {
		if count[c] > 0 {
			count[c]--
			continue
		}
		missing = append(missing, c)
	}
	for _, c := range got {
		if count[c] > 0 {
			count[c]--
			extra = append(extra, c)
		}
	}
	return missing, extra
}

// why is the explanation attached to every failure of the list above, because
// the person who trips it is editing YAML and has no reason to have read this
// file's package comment.
const why = "" +
	"The Makefile defines how the whole tree is tested, and a copy in the workflow is a\n" +
	"copy that stops tracking it. That is the defect: a commit gave `make race` " +
	"an explicit\n" +
	"-timeout 30m because node/mempool exceeds Go's ten-minute default under the race\n" +
	"detector, CI kept its own inline command, and the fix never reached the job that\n" +
	"was failing.\n" +
	"If this command should call a Makefile target, call it: `make test`, `make race`.\n" +
	"If it genuinely should not — a separate module, or a runner without GNU make —\n" +
	"update the list in this test and say why in the pull request."

// show renders a command the way a reader needs it, spelling out the working
// directory: the same text is a different fact at the repository root and inside
// `desktop/`, and a failure has to say which one it is looking at.
func show(c command) string {
	wd := "at the repository root, so ./... is the root module"
	if c.WorkingDir != "" {
		wd = "working-directory: " + c.WorkingDir
	}
	return "job " + c.Job + " (" + wd + "): " + c.Text
}

// TestTheWholeTreeSuitesAreInvokedThroughTheMakefile is the positive half.
//
// The property: **the `build` job reaches the whole-tree suites by calling the
// Makefile targets that define them.**
//
// The list above forbids the inline form; on its own it is satisfied by deleting
// the steps entirely, which is a worse defect than the one it guards. This one
// requires them present, by exact equality — an earlier `strings.Contains` was
// satisfied by `make test-randomx`, a target this Makefile really defines, so a
// build job that had stopped running the whole-tree suites passed the check that
// exists to notice exactly that.
func TestTheWholeTreeSuitesAreInvokedThroughTheMakefile(t *testing.T) {
	cmds := readWorkflowCommands(t)

	for _, target := range []string{"make test", "make race"} {
		found := false
		for _, c := range cmds {
			if c.Job == "build" && c.WorkingDir == "" && c.Text == target {
				found = true
				break
			}
		}
		if !found {
			t.Errorf("no step of the build job runs exactly %q.\n"+
				"The whole-tree suites must be invoked through the Makefile, which is where\n"+
				"the flags they need are defined and explained.", target)
		}
	}
}

// TestTheMakefileTargetsStillRunWhatCICallsThemFor pins the thing the
// duplication was actually about, at its source.
//
// The property: **`make test` runs the whole tree, and `make race` runs it with
// `-race` and an explicit `-timeout`.**
//
// The two tests above route CI through the target. They say nothing about
// whether the target still carries the flag that made routing worth doing — and
// a `race:` recipe that lost its `-timeout` would satisfy both of them while
// putting CI back at Go's ten-minute default, which is the original defect
// wearing the fix's clothes. The Makefile is read directly, because the flag is
// the ground truth here and `make -n` would only report it second-hand.
func TestTheMakefileTargetsStillRunWhatCICallsThemFor(t *testing.T) {
	b, err := os.ReadFile(filepath.Clean(makefilePath))
	if err != nil {
		t.Fatalf("reading the Makefile: %v", err)
	}

	// The `test` target, pinned for the reason the golden list exists: routing CI
	// through a target is worth nothing if the target stops running the suite.
	// Replacing `test:`'s recipe with `@echo 'skipping the suite'` left every
	// assertion in this file green — a CI running no whole-tree suite at all,
	// which is the state this file's own comments call strictly worse than the
	// duplication itself, reachable from one file over.
	testRecipe, ok := recipeFor(string(b), "test")
	if !ok {
		t.Fatal("the Makefile has no `test:` target; CI was routed through it")
	}
	if !strings.Contains(testRecipe, treeWide) {
		t.Errorf("the test target no longer runs the whole tree:\n%s\n"+
			"`ci.yml` calls `make test` instead of an inline `go test ./...`, so\n"+
			"this recipe is now the only definition of what the whole-tree suite is.",
			testRecipe)
	}

	recipe, ok := recipeFor(string(b), "race")
	if !ok {
		t.Fatal("the Makefile has no `race:` target; CI was routed through it")
	}
	if !strings.Contains(recipe, "-race") {
		t.Errorf("the race target does not pass -race:\n%s", recipe)
	}
	if !strings.Contains(recipe, "-timeout") {
		t.Errorf("the race target no longer passes an explicit -timeout:\n%s\n"+
			"Go's ten-minute default is not enough for node/mempool's eviction suite under\n"+
			"the race detector — measured at 709s and then 984s on darwin/arm64, and cut at\n"+
			"exactly 600s on the CI runner. Removing the flag restores the\n"+
			"failure that routing CI through this target was meant to fix.\n"+
			"The VALUE is deliberately not checked, so that the ceiling can be lowered\n"+
			"again once node/mempool's own runtime leaves room for it.",
			recipe)
	}
}

// parseRuns reads the workflow's steps, split from the file read so that
// TestTheParserSeesTheFormsTheWorkflowUses can exercise it against a fixture
// rather than against whatever syntax the real workflow happens to use today.
//
// It works a step at a time rather than a line at a time. A step is buffered in
// full, its `working-directory:` is found wherever in the step it sits, and only
// then are its commands read. The line-at-a-time version required
// `working-directory:` to appear *above* `run:`, which YAML does not require —
// mapping keys are unordered — so the same step was judged differently depending
// on the order two keys were typed in.
func parseRuns(src string, resolve resolver) []command {
	var cmds []command
	eachStep(src, resolve, func(job, defaultWD string, step []string) {
		cmds = append(cmds, commandsInStep(job, defaultWD, step)...)
	})
	return cmds
}

// eachStep walks the workflow's steps, calling fn with the job and default
// working directory each one runs under. It is shared by parseRuns and by the
// blindness checks, so that those cannot disagree with the reading they are
// meant to be auditing.
func eachStep(src string, resolve resolver, fn func(job, defaultWD string, step []string)) {
	lines := strings.Split(src, "\n")

	inJobs, inSteps := false, false
	job, jobDefaultWD := "", ""
	stepIndent := -1
	var step []string

	flush := func() {
		if len(step) > 0 {
			fn(job, jobDefaultWD, step)
			step = nil
		}
	}

	for _, line := range lines {
		if jobsKey.MatchString(line) {
			inJobs = true
			continue
		}
		if !inJobs {
			continue
		}
		if m := jobHeader.FindStringSubmatch(line); m != nil {
			flush()
			job, jobDefaultWD, inSteps, stepIndent = m[1], "", false, -1
			continue
		}
		if !inSteps {
			// Before `steps:`, the only thing worth reading is the job's
			// `defaults.run.working-directory`, which applies to every step
			// that does not set its own. Ignoring it made a job using the
			// defaults block — valid, and common on GitHub — misattributed.
			if m := workingDir.FindStringSubmatch(line); m != nil {
				jobDefaultWD = m[1]
			}
			// A job whose body is a `uses:` has no steps of its own: it runs
			// the called workflow's. Its steps are reported under THIS job's
			// name, which is the one the golden list names and the one CI
			// shows. The called workflow supplies its own working directories,
			// so nothing of this job's context carries into it.
			if m := localWorkflowCall.FindStringSubmatch(line); m != nil && resolve != nil {
				if called, ok := resolve(m[1]); ok {
					caller := job
					eachStep(called, resolve, func(_, wd string, step []string) {
						fn(caller, wd, step)
					})
				}
				continue
			}
			if stepsKey.MatchString(line) {
				inSteps = true
			}
			continue
		}
		if m := stepStart.FindStringSubmatch(line); m != nil {
			indent := len(m[1])
			if stepIndent == -1 {
				stepIndent = indent
			}
			if indent == stepIndent {
				flush()
			}
		}
		step = append(step, line)
	}
	flush()
}

// commandsInStep reads one step's lines: its working directory first, wherever
// it appears, then its commands.
func commandsInStep(job, defaultWD string, step []string) []command {
	// A step's first line carries the `- ` that begins it, and in `- run: …`
	// that dash occupies the column the key would otherwise start at. So the
	// dash is replaced by two spaces, putting `run:` at the same indent as the
	// sibling keys of a named step.
	//
	// Without this, a step written without a `name` was invisible: `- run: go
	// test -race -timeout 5m ./...` matched no key and produced no command at
	// all. Unnamed steps are ordinary GitHub — this workflow already has several
	// unnamed `- uses:` steps — so it is drift, not an adversary.
	//
	// Only the FIRST line is normalised. A `- ` deeper in the step belongs to a
	// nested list or to block-scalar content, and rewriting those would change
	// the text of the very commands being compared.
	step = append([]string(nil), step...)
	if len(step) > 0 {
		if m := stepStart.FindStringSubmatch(step[0]); m != nil {
			step[0] = m[1] + "  " + step[0][len(m[1])+2:]
		}
	}

	wd := defaultWD
	for _, line := range step {
		if m := workingDir.FindStringSubmatch(line); m != nil {
			wd = m[1]
			break
		}
	}

	// A step's own keys sit two spaces in from its `- `. Anything deeper is a
	// nested mapping — a composite action's `with:` block can carry a `run:`
	// input of its own — and reading those as commands churns the golden list
	// with strings that are data rather than commands CI runs.
	keyIndent := -1
	if len(step) > 0 {
		keyIndent = len(step[0]) - len(strings.TrimLeft(step[0], " "))
	}

	var cmds []command
	for i := 0; i < len(step); i++ {
		m := runLine.FindStringSubmatch(step[i])
		if m == nil {
			continue
		}
		indent, rest := len(m[1]), m[2]
		if keyIndent >= 0 && indent != keyIndent {
			continue
		}
		bs := blockScalar.FindStringSubmatch(rest)
		if bs == nil {
			if rest != "" {
				cmds = append(cmds, command{Job: job, WorkingDir: wd, Text: rest})
			}
			continue
		}
		body, next := blockBody(step, i, indent)
		i = next
		for _, text := range splitCommands(body, bs[1] == ">") {
			cmds = append(cmds, command{Job: job, WorkingDir: wd, Text: text})
		}
	}
	return cmds
}

// blockBody returns the lines belonging to a block scalar introduced at index i,
// and the index of its last line. The block is the following lines indented
// further than the `run:` key itself; blank lines belong to it.
func blockBody(step []string, i, indent int) ([]string, int) {
	var body []string
	for i+1 < len(step) {
		next := step[i+1]
		if strings.TrimSpace(next) != "" &&
			len(next)-len(strings.TrimLeft(next, " ")) <= indent {
			break
		}
		body = append(body, next)
		i++
	}
	return body, i
}

// splitCommands turns a block scalar's lines into the commands it actually runs.
//
// Three joins happen here, and the first two closed blind spots found by
// mutating the real workflow. The first version treated every physical line as
// one command, which is right only for a literal block of single-line commands.
//
//	backslash   `go test -race \` / `  -timeout 5m ./...` is ONE command that
//	            the line-at-a-time reader saw as two. Nothing clever: it is how
//	            a long command gets written when it stops fitting.
//
//	folded      `run: >` means the lines ARE one command — that is the whole
//	            meaning of the indicator. The fixture that was supposed to pin
//	            folded blocks used a one-line body, so it could not see this.
//
//	comments    a shell `#` line is prose, not a command, for the reason
//	            recipeFor strips Make recipe comments.
func splitCommands(body []string, folded bool) []string {
	var out []string
	var cur []string
	end := func() {
		if len(cur) > 0 {
			out = append(out, strings.Join(cur, " "))
			cur = nil
		}
	}
	for _, line := range body {
		text := strings.TrimSpace(line)
		if text == "" {
			end() // a blank line ends a folded paragraph and a continuation.
			continue
		}
		if strings.HasPrefix(text, "#") {
			end()
			continue
		}
		if strings.HasSuffix(text, `\`) {
			cur = append(cur, strings.TrimSpace(strings.TrimSuffix(text, `\`)))
			continue
		}
		cur = append(cur, text)
		if !folded {
			end()
		}
	}
	end()
	return out
}

// TestTheParserSeesTheFormsTheWorkflowUses is the anti-vacuity test for the
// reading apparatus.
//
// The property: **parseRuns reports the command a step runs, with the job and
// working directory it runs under, for every YAML form this workflow uses.**
//
// The assertions above all read the real workflow, so they can only ever observe
// the syntax that file happens to use today. That is how four separate blind
// spots shipped: a `run: |` block whose body was never read, a `\` continuation
// split into two half-commands, a folded body split the same way, and a job id
// containing `_` that made the parser attribute one job's steps to another.
// Each of them let a whole-tree race command sit in the file, at a five-minute
// timeout, with every test here green.
//
// So the parser is exercised against a fixture carrying every form at once. A
// blind spot fixed without being pinned is a blind spot moved.
func TestTheParserSeesTheFormsTheWorkflowUses(t *testing.T) {
	const fixture = `on:
  push:
    branches: [main]
  pull_request:
jobs:
  build:
    steps:
      - name: single line
        run: make test
      - name: literal block
        run: |
          # a shell comment is prose, not a command
          go test -race ./...
          echo done
      - name: a backslash continues one command onto the next line
        run: |
          go test -race \
            -timeout 5m ./...
      - name: chomped block
        run: |-
          go vet ./...
      - name: a folded block is ONE command, however many lines it occupies
        run: >
          go test -race -timeout 5m
          ./...
      - name: after the block
        run: make race
      - run: go vet -tags x ./...
      - run: |
          go test -tags y ./...
  windows:
    steps:
      - name: inline
        run: go test ./...
  reproducible_check:
    steps:
      - name: an underscore is a legal job id, and this job is not windows
        run: go test -race ./...
  defaulted:
    defaults:
      run:
        working-directory: desktop
    steps:
      - name: the job default applies
        run: go test -tags desktop ./...
  desktop:
    steps:
      - name: no working directory, so the repository root
        run: go test ./...
      - name: keys are unordered, so this one sits BELOW its run
        run: go test -tags desktop ./...
        working-directory: desktop
      - name: the scope does not leak to the next step
        run: go test ./...
  platform:
    uses: ./.github/workflows/reusable.yml
  published:
    uses: some/action@v1
`
	// The workflow `platform` calls. Its own job id differs from the calling
	// job's on purpose: the commands must arrive under the CALLER's name, since
	// that is the one the golden list names and the one CI shows.
	const reusable = `on:
  workflow_call:
jobs:
  windows:
    steps:
      - name: at the repository root
        run: go test ./...
      - name: in the separate module
        working-directory: desktop
        run: go test -tags desktop ./...
`
	resolve := func(ref string) (string, bool) {
		if ref != "./.github/workflows/reusable.yml" {
			return "", false
		}
		return reusable, true
	}
	want := []command{
		{"build", "", "make test"},
		{"build", "", "go test -race ./..."},
		{"build", "", "echo done"},
		// The backslash join: one command, not two half-commands.
		{"build", "", "go test -race -timeout 5m ./..."},
		{"build", "", "go vet ./..."},
		// The folded join: `>` means these lines ARE one command.
		{"build", "", "go test -race -timeout 5m ./..."},
		{"build", "", "make race"},
		// Unnamed steps. The `- ` sits where the key would, and both forms
		// produced no command at all before it was normalised away.
		{"build", "", "go vet -tags x ./..."},
		{"build", "", "go test -tags y ./..."},
		{"windows", "", "go test ./..."},
		// Not attributed to `windows`, which is what an unmatched job header
		// used to do.
		{"reproducible_check", "", "go test -race ./..."},
		// defaults.run.working-directory, with no per-step key.
		{"defaulted", "desktop", "go test -tags desktop ./..."},
		{"desktop", "", "go test ./..."},
		// The key sits below its `run:`, which YAML permits.
		{"desktop", "desktop", "go test -tags desktop ./..."},
		// A working-directory belongs to ONE step and does not leak forward.
		{"desktop", "", "go test ./..."},
		// A job that is a call to a workflow in this repository. Its steps are
		// reported under `platform`, the calling job, not under `windows`, the
		// job id inside the called file.
		{"platform", "", "go test ./..."},
		{"platform", "desktop", "go test -tags desktop ./..."},
		// `published` contributes nothing: a `uses:` outside this repository
		// names an action, which has no steps to read here.
	}

	got := parseRuns(fixture, resolve)
	if len(got) != len(want) {
		t.Fatalf("got %d commands, want %d:\ngot  %+v\nwant %+v", len(got), len(want), got, want)
	}
	for i := range want {
		if got[i] != want[i] {
			t.Errorf("command %d: got %+v, want %+v", i, got[i], want[i])
		}
	}

	// The block indicator itself must never be reported as a command.
	for _, c := range got {
		if blockScalar.MatchString(c.Text) {
			t.Errorf("the parser reported a block indicator %q as a command", c.Text)
		}
	}
}

// recipeFor returns the COMMAND lines of a Make target: the tab-indented lines
// following `name:`, with the recipe's own comments removed.
//
// Dropping the comments is not tidiness, it is the whole correctness of this
// helper. A Make recipe comments with a tab followed by `#`, and `race:`'s
// comment block spends sixteen lines explaining itself. A version that returned
// those comments let an assertion match the *prose about a flag* instead of the
// flag. Measured, on this Makefile, with the comments included:
//
//	delete `-timeout 30m` from the command, search for "-timeout"  →  not found
//	delete `-race`        from the command, search for "-race"     →  FOUND
//
// So it was the `-race` assertion that was vacuous, not the timeout one: the
// prose writes "an explicit timeout" without the hyphen, but it does write
// `-race` when quoting a measurement, and that one backticked mention satisfied
// the check after the flag itself was gone.
func recipeFor(makefile, name string) (string, bool) {
	lines := strings.Split(makefile, "\n")
	for i, line := range lines {
		if !strings.HasPrefix(line, name+":") {
			continue
		}
		var recipe []string
		for _, next := range lines[i+1:] {
			// A blank line does not end a recipe — GNU make ignores it — and
			// treating it as a terminator truncated the recipe at the blank,
			// firing both assertions on a target that satisfies both. That is
			// the false positive CONTRIBUTING.md calls worse than silence.
			if strings.TrimSpace(next) == "" {
				continue
			}
			if !strings.HasPrefix(next, "\t") {
				break // the recipe ends at the first line that is not tab-indented.
			}
			if strings.HasPrefix(strings.TrimSpace(next), "#") {
				continue // a recipe comment: prose, not a command.
			}
			recipe = append(recipe, next)
		}
		return strings.Join(recipe, "\n"), true
	}
	return "", false
}
